sudo: false
language: haskell
ghc:
  - '7.4'
  - '7.6'
  # - 7.8 # language-c fails to install
  # - '7.10' # Avoid 7.10 being parsed as float 7.1
addons:
  apt:
    packages:
    - libsndfile1-dev
install:
  - cabal install c2hs
  - cabal install --enable-tests
deploy:
  provider: hackage
  username: StefanKersten
  password:
    secure: JmHk+reqqnRlnvhSQt76BOfp8xq3F58l8KJ6UNDnM2yVwh9Kcz30sx0iSISOi51kc+F/OST1uwr1cn5mu8YC6VaEqXAzUirFYOR1gbwRPEnxYRgIU25RZpsDBV2/nNSJM+q/rGNIOgvJ659KSmv5LxsW0SgS4JAEJ17wpfKaIuc=
  on:
    repo: kaoskorobase/hsndfile
    branch: master
